-- AlterEnum
ALTER TYPE "StationType" ADD VALUE 'TRUE_FALSE';
ALTER TYPE "StationType" ADD VALUE 'FILL_BLANK';
ALTER TYPE "StationType" ADD VALUE 'ODD_ONE_OUT';
ALTER TYPE "StationType" ADD VALUE 'PICTURE_QUIZ';
